name: Refresh UVA chart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"  # midnight UTC

jobs:
  update-chart:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install NordVPN
      run: |
          sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)

    - name: Quick Connect to VPN
      run: |
        sudo nordvpn login --token $TOKEN
        sudo nordvpn connect
      env:
        TOKEN: ${{ secrets.TOKEN }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
      working-directory: scripts

    - name: Retrieve Kattis Data 
      run: python get_Kattis_data.py
      working-directory: scripts
      env:
        KATTIS_EMAIL: ${{ secrets.KATTIS_EMAIL }}
        KATTIS_PASSWORD: ${{ secrets.KATTIS_PASSWORD }}

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
      working-directory: scripts
      
      
    - name: Generate UVA chart
      run: node generate_UVA_report.cjs
      working-directory: scripts

    - name: Generate Codeforces chart
      run: node generate_Codeforces_report.cjs
      working-directory: scripts

    - name: Generate Kattis chart
      run: node generate_Kattis_report.cjs
      working-directory: scripts

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add scripts/out/UVA_donut_chart.svg
        git add scripts/out/Codeforces_donut_chart.svg
        git add scripts/out/Kattis_donut_chart.svg
        git diff --cached --quiet || (git commit -m "Updated statistics" && git push)
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
